# Autogenerated wrapper script for stb_jll for any
JLLWrappers.@generate_wrapper_header("stb")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
